### Step 1: Installation of List of Frameworks

In [1]:
!pip install gradio smolagents python-dotenv sqlalchemy

Collecting gradio
  Downloading gradio-5.22.0-py3-none-any.whl.metadata (16 kB)
Collecting smolagents
  Downloading smolagents-1.12.0-py3-none-any.whl.metadata (14 kB)
Collecting python-dotenv
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.11/dist-packages (2.0.39)
Collecting aiofiles<24.0,>=22.0 (from gradio)
  Downloading aiofiles-23.2.1-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (4.9.0)
Collecting fastapi<1.0,>=0.115.2 (from gradio)
  Downloading fastapi-0.115.12-py3-none-any.whl.metadata (27 kB)
Collecting ffmpy (from gradio)
  Downloading ffmpy-0.5.0-py3-none-any.whl.metadata (3.0 kB)
Collecting gradio-client==1.8.0 (from gradio)
  Downloading gradio_client-1.8.0-py3-none-any.whl.metadata (7.1 kB)
Collecting groovy~=0.1 (from gradio)
  Downloading groovy-0.1.2-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: httpx>=0.24.1 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub>=0.28.1 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.29.3)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.0.2)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.0.2)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.10.15)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from gradio) (24.2)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (11.1.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.10.6)
Collecting pydub (from gradio)
  Downloading pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting python-multipart>=0.0.18 (from gradio)
  Downloading python_multipart-0.0.20-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (6.0.2)
Collecting ruff>=0.9.3 (from gradio)
  Downloading ruff-0.11.2-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (25 kB)
Collecting safehttpx<0.2.0,>=0.1.6 (from gradio)
  Downloading safehttpx-0.1.6-py3-none-any.whl.metadata (4.2 kB)
Collecting semantic-version~=2.0 (from gradio)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting starlette<1.0,>=0.40.0 (from gradio)
  Downloading starlette-0.46.1-py3-none-any.whl.metadata (6.2 kB)
Collecting tomlkit<0.14.0,>=0.12.0 (from gradio)
  Downloading tomlkit-0.13.2-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.15.2)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (4.12.2)
Collecting uvicorn>=0.14.0 (from gradio)
  Downloading uvicorn-0.34.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from gradio-client==1.8.0->gradio) (2025.3.0)
Requirement already satisfied: websockets<16.0,>=10.0 in /usr/local/lib/python3.11/dist-packages (from gradio-client==1.8.0->gradio) (14.2)
Requirement already satisfied: requests>=2.32.3 in /usr/local/lib/python3.11/dist-packages (from smolagents) (2.32.3)
Requirement already satisfied: rich>=13.9.4 in /usr/local/lib/python3.11/dist-packages (from smolagents) (13.9.4)
Collecting pandas<3.0,>=1.0 (from gradio)
  Downloading pandas-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 2.8 MB/s eta 0:00:00
Collecting markdownify>=0.14.1 (from smolagents)
  Downloading markdownify-1.1.0-py3-none-any.whl.metadata (9.1 kB)
Collecting duckduckgo-search>=6.3.7 (from smolagents)
  Downloading duckduckgo_search-7.5.3-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5.0,>=3.0->gradio) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio<5.0,>=3.0->gradio) (1.3.1)
Requirement already satisfied: click>=8.1.8 in /usr/local/lib/python3.11/dist-packages (from duckduckgo-search>=6.3.7->smolagents) (8.1.8)
Collecting primp>=0.14.0 (from duckduckgo-search>=6.3.7->smolagents)
  Downloading primp-0.14.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: lxml>=5.3.0 in /usr/local/lib/python3.11/dist-packages (from duckduckgo-search>=6.3.7->smolagents) (5.3.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx>=0.24.1->gradio) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.24.1->gradio) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.24.1->gradio) (0.14.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (3.18.0)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (4.67.1)
Requirement already satisfied: beautifulsoup4<5,>=4.9 in /usr/local/lib/python3.11/dist-packages (from markdownify>=0.14.1->smolagents) (4.13.3)
Requirement already satisfied: six<2,>=1.15 in /usr/local/lib/python3.11/dist-packages (from markdownify>=0.14.1->smolagents) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0,>=1.0->gradio) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.0->gradio) (2.27.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.3->smolagents) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.3->smolagents) (2.3.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=13.9.4->smolagents) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=13.9.4->smolagents) (2.18.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4<5,>=4.9->markdownify>=0.14.1->smolagents) (2.6)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=13.9.4->smolagents) (0.1.2)
Downloading gradio-5.22.0-py3-none-any.whl (46.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 11.2 MB/s eta 0:00:00
Downloading gradio_client-1.8.0-py3-none-any.whl (322 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.2/322.2 kB 8.8 MB/s eta 0:00:00
Downloading smolagents-1.12.0-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.3/105.3 kB 7.8 MB/s eta 0:00:00
Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Downloading aiofiles-23.2.1-py3-none-any.whl (15 kB)
Downloading duckduckgo_search-7.5.3-py3-none-any.whl (20 kB)
Downloading fastapi-0.115.12-py3-none-any.whl (95 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.2/95.2 kB 5.3 MB/s eta 0:00:00
Downloading groovy-0.1.2-py3-none-any.whl (14 kB)
Downloading markdownify-1.1.0-py3-none-any.whl (13 kB)
Downloading pandas-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 20.2 MB/s eta 0:00:00
Downloading python_multipart-0.0.20-py3-none-any.whl (24 kB)
Downloading ruff-0.11.2-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 22.9 MB/s eta 0:00:00
Downloading safehttpx-0.1.6-py3-none-any.whl (8.7 kB)
Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Downloading starlette-0.46.1-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 5.0 MB/s eta 0:00:00
Downloading tomlkit-0.13.2-py3-none-any.whl (37 kB)
Downloading uvicorn-0.34.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 4.1 MB/s eta 0:00:00
Downloading ffmpy-0.5.0-py3-none-any.whl (6.0 kB)
Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Downloading primp-0.14.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 22.5 MB/s eta 0:00:00
Installing collected packages: pydub, uvicorn, tomlkit, semantic-version, ruff, python-multipart, python-dotenv, primp, groovy, ffmpy, aiofiles, starlette, pandas, markdownify, duckduckgo-search, smolagents, safehttpx, gradio-client, fastapi, gradio
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.2.3 which is incompatible.
Successfully installed aiofiles-23.2.1 duckduckgo-search-7.5.3 fastapi-0.115.12 ffmpy-0.5.0 gradio-5.22.0 gradio-client-1.8.0 groovy-0.1.2 markdownify-1.1.0 pandas-2.2.3 primp-0.14.0 pydub-0.25.1 python-dotenv-1.0.1 python-multipart-0.0.20 ruff-0.11.2 safehttpx-0.1.6 semantic-version-2.10.0 smolagents-1.12.0 starlette-0.46.1 tomlkit-0.13.2 uvicorn-0.34.0

In [16]:
%%writefile database.py
# List of Framework
from sqlalchemy import (
    create_engine,
    MetaData,
    Table,
    Column,
    String,
    Integer,
    Float,
    insert,
    text,
)

# Step-1: Use a Persistent SQLite database file.
engine = create_engine("sqlite:///database.db")
metadata_obj = MetaData()

# Step-2: Define the `receipts` table
receipts = Table(
    "receipts",
    metadata_obj,
    Column("receipt_id", Integer, primary_key=True),
    Column("customer_name", String(16)),
    Column("price", Float),
    Column("tip", Float),
)

# Step-3: Create the table if it is doesn't exist
metadata_obj.create_all(engine)

# Step-4: Function to insert rows into the table
def insert_rows_into_table(rows, table):
    with engine.begin() as connection:
        connection.execute(insert(table), rows)


# Step-5: Insert Sample Data if table is empty
with engine.connect() as conn:
    result = conn.execute(text("SELECT COUNT(*) FROM receipts"))
    count = result.scalar()
    if count == 0:
        rows = [
            {"receipt_id": 1, "customer_name": "Ezekiel Frost", "price": 10.50, "tip": 2.00},
            {"receipt_id": 2, "customer_name": "Marla Dune", "price": 23.75, "tip": 4.50},
            {"receipt_id": 3, "customer_name": "Thorne Blackwood", "price": 55.20, "tip": 6.25},
            {"receipt_id": 4, "customer_name": "Selene Ashford", "price": 32.10, "tip": 3.50},
            {"receipt_id": 5, "customer_name": "Vesper Hawthorne", "price": 19.80, "tip": 2.75},
            {"receipt_id": 6, "customer_name": "Jaxon Raines", "price": 48.60, "tip": 5.00},
            {"receipt_id": 7, "customer_name": "Liora Vale", "price": 27.45, "tip": 3.00},
            {"receipt_id": 8, "customer_name": "Orion Finch", "price": 60.25, "tip": 7.50},
            {"receipt_id": 9, "customer_name": "Calista Morrigan", "price": 38.90, "tip": 4.25},
            {"receipt_id": 10, "customer_name": "Dorian Storm", "price": 50.75, "tip": 6.75},
            {"receipt_id": 11, "customer_name": "Lucian Crowe", "price": 11.90, "tip": 1.50},
            {"receipt_id": 12, "customer_name": "Eris Delacroix", "price": 29.95, "tip": 3.75},
            {"receipt_id": 13, "customer_name": "Zane Evermore", "price": 45.80, "tip": 5.50},
            {"receipt_id": 14, "customer_name": "Isolde Winter", "price": 31.20, "tip": 2.25},
            {"receipt_id": 15, "customer_name": "Galen Hallow", "price": 18.60, "tip": 2.00},
            {"receipt_id": 16, "customer_name": "Sable Whitmore", "price": 54.35, "tip": 6.00},
            {"receipt_id": 17, "customer_name": "Cassian Vex", "price": 28.10, "tip": 3.25},
            {"receipt_id": 18, "customer_name": "Selwyn Fox", "price": 61.45, "tip": 7.75},
            {"receipt_id": 19, "customer_name": "Thalia Rune", "price": 37.20, "tip": 4.00},
            {"receipt_id": 20, "customer_name": "Draven Nocturne", "price": 49.95, "tip": 6.25},
            {"receipt_id": 21, "customer_name": "Kieran Wolfe", "price": 12.75, "tip": 1.75},
            {"receipt_id": 22, "customer_name": "Ember Sterling", "price": 30.60, "tip": 3.50},
            {"receipt_id": 23, "customer_name": "Valko Nightshade", "price": 47.90, "tip": 5.75},
            {"receipt_id": 24, "customer_name": "Ronan Greaves", "price": 33.40, "tip": 3.00},
            {"receipt_id": 25, "customer_name": "Lyra Voss", "price": 20.50, "tip": 2.25},
            {"receipt_id": 26, "customer_name": "Caius Everdark", "price": 53.25, "tip": 6.50},
            {"receipt_id": 27, "customer_name": "Eowyn Vale", "price": 26.80, "tip": 2.75},
            {"receipt_id": 28, "customer_name": "Phoenix Ashen", "price": 59.30, "tip": 7.00},
            {"receipt_id": 29, "customer_name": "Leif Hawthorne", "price": 36.15, "tip": 3.75},
            {"receipt_id": 30, "customer_name": "Zephyr Sterling", "price": 48.75, "tip": 6.00},
            {"receipt_id": 31, "customer_name": "Solene Ardent", "price": 13.90, "tip": 1.25},
            {"receipt_id": 32, "customer_name": "Orpheus Dawn", "price": 31.95, "tip": 2.50},
            {"receipt_id": 33, "customer_name": "Nyx Holloway", "price": 46.85, "tip": 5.25},
            {"receipt_id": 34, "customer_name": "Rowan Nightshade", "price": 32.75, "tip": 3.00},
            {"receipt_id": 35, "customer_name": "Dante Crowley", "price": 22.50, "tip": 2.00},
            {"receipt_id": 36, "customer_name": "Sylas Vex", "price": 55.90, "tip": 6.75},
            {"receipt_id": 37, "customer_name": "Isabeau Winters", "price": 27.85, "tip": 3.25},
            {"receipt_id": 38, "customer_name": "Astra Everhart", "price": 62.10, "tip": 8.00},
            {"receipt_id": 39, "customer_name": "Tiberius Dusk", "price": 39.60, "tip": 4.50},
            {"receipt_id": 40, "customer_name": "Eldric Thorn", "price": 50.95, "tip": 6.25},
        ]
        insert_rows_into_table(rows, receipts)

Overwriting database.py

In [17]:
%%writefile sqlagent.py
import os
import pandas as pd
import gradio as gr
from sqlalchemy import text
from database import engine, receipts
from smolagents import tool, CodeAgent, HfApiModel

def get_receipts_table():
    """
    Fetches all data from the 'receipts' table and returns it as a Pandas DataFrame.
    Returns:
        A Pandas DataFrame containing all receipt data.
    """
    try:
        with engine.connect() as con:
            result = con.execute(text("SELECT * FROM receipts"))
            rows = result.fetchall()

        if not rows:
            return pd.DataFrame(columns=["receipt_id", "customer_name", "price", "tip"])

        # Convert rows into a DataFrame
        df = pd.DataFrame(rows, columns=["receipt_id", "customer_name", "price", "tip"])
        return df

    except Exception as e:
        return pd.DataFrame({"Error": [str(e)]})  # Return error message in DataFrame format

@tool
def sql_engine(query: str) -> str:
    """
    Executes an SQL query on the 'receipts' table and returns formatted results.
    Args:
        query: The SQL query to execute.
    Returns:
        Query result as a formatted string.
    """
    try:
        with engine.connect() as con:
            rows = con.execute(text(query)).fetchall()

        if not rows:
            return "No results found."

        if len(rows) == 1 and len(rows[0]) == 1:
            return str(rows[0][0])  # Convert numerical result to string

        return "\n".join([", ".join(map(str, row)) for row in rows])

    except Exception as e:
        return f"Error: {str(e)}"

def query_sql(user_query: str) -> str:
    """
    Converts natural language input to an SQL query using CodeAgent
    and returns the execution results.
    Args:
        user_query: The user's request in natural language.
    Returns:
        The query result from the database as a formatted string.
    """

    schema_info = (
        "The database has a table named 'receipts' with the following schema:\n"
        "- receipt_id (INTEGER, primary key)\n"
        "- customer_name (VARCHAR(16))\n"
        "- price (FLOAT)\n"
        "- tip (FLOAT)\n"
        "Generate a valid SQL SELECT query using ONLY these column names.\n"
        "DO NOT explain your reasoning, and DO NOT return anything other than the SQL query itself."
    )

    generated_sql = agent.run(f"{schema_info} Convert this request into SQL: {user_query}")

    if not isinstance(generated_sql, str):
        return f"{generated_sql}"  # Handle unexpected numerical result

    print(f"{generated_sql}")

    # if not generated_sql.strip().lower().startswith(("select", "show", "pragma")):
    #     return "Error: Only SELECT queries are allowed."

    result = sql_engine(generated_sql)

    print(f"{result}")

    try:
        float_result = float(result)
        return f"{float_result:.2f}"
    except ValueError:
        return result

def handle_query(user_input: str) -> str:
    """
    Calls query_sql, captures the output, and directly returns it to the UI.
    Args:
        user_input: The user's natural language question.
    Returns:
        The SQL query result as a plain string to be displayed in the UI.
    """
    return query_sql(user_input)

agent = CodeAgent(
    tools=[sql_engine],
    model=HfApiModel(model_id="Qwen/Qwen2.5-Coder-32B-Instruct", token="hf-key...."),
)

with gr.Blocks() as demo:
    gr.Markdown("""
# Plain Text Query Interface
This tool allows you to query a receipts database using natural language. Simply type your question into the input box, and the tool will generate and execute an SQL query to retrieve relevant data. The results will be displayed in the output box.
### Usage:
1. Enter a question related to the receipts data in the text box.
2. The tool will convert your question into an SQL query and execute it.
3. The result will be displayed in the output box.
> The current receipts table is also displayed for reference.
""")

    with gr.Row():
        with gr.Column(scale=1):
            user_input = gr.Textbox(label="Ask a question about the data")
            query_output = gr.Textbox(label="Result")

        with gr.Column(scale=2):
            gr.Markdown("### Receipts Table")
            receipts_table = gr.Dataframe(value=get_receipts_table(), label="Receipts Table")

    user_input.change(fn=handle_query, inputs=user_input, outputs=query_output)

    demo.load(fn=get_receipts_table, outputs=receipts_table)

if __name__ == "__main__":
    demo.launch(server_name="0.0.0.0", server_port=7860, share=True)

Overwriting sqlagent.py

In [18]:
!npm install localtunnel

⠙⠹⠸⠼⠴⠦
up to date, audited 23 packages in 884ms
⠦
⠦3 packages are looking for funding
⠦  run `npm fund` for details
⠦
2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
⠦

In [22]:
# !python3 sqlagent.py & npx localtunnel --port 8501
%%writefile new_sqlagent.py
import os
import gradio as gr
from sqlalchemy import text
from smolagents import tool, CodeAgent, HfApiModel
import pandas as pd
from database import engine, receipts

# Function to fetch receipt data from the database
def get_receipts_table():
    try:
        with engine.connect() as con:
            result = con.execute(text("SELECT * FROM receipts"))
            rows = result.fetchall()

        if not rows:
            return pd.DataFrame(columns=["receipt_id", "customer_name", "price", "tip"])

        df = pd.DataFrame(rows, columns=["receipt_id", "customer_name", "price", "tip"])
        return df

    except Exception as e:
        return pd.DataFrame({"Error": [str(e)]})  # Return error message in DataFrame format

# def sanitize_query(query: str) -> str:
#     """
#     Sanitizes the query to ensure that values are properly quoted and formatted.
#     Args:
#         query (str): The raw SQL query from user input.
#     Returns:
#         str: The sanitized query.
#     """
#     query = query.replace("'", "''")  # Escape single quotes by doubling them
#     return query

@tool
def sql_engine(query: str) -> str:
    """
    Executes an SQL query on the 'receipts' table and returns formatted results.
    Args:
        query (str): The SQL query to execute.
    Returns:
        str: The result of the SQL query as a formatted string.
    """
    try:
        # query = sanitize_query(query)  # Sanitize the query before execution

        with engine.connect() as con:
            rows = con.execute(text(query)).fetchall()

        if not rows:
            return "No results found."

        if len(rows) == 1 and len(rows[0]) == 1:
            return str(rows[0][0])  # Convert numerical result to string

        return "\n".join([", ".join(map(str, row)) for row in rows])

    except Exception as e:
        return f"Error: {str(e)}"

# Function to handle natural language query and convert it to SQL
def query_sql(user_query: str) -> str:
    schema_info = (
        "The database has a table named 'receipts' with the following schema:\n"
        "- receipt_id (INTEGER, primary key)\n"
        "- customer_name (VARCHAR(16))\n"
        "- price (FLOAT)\n"
        "- tip (FLOAT)\n"
        "Generate a valid SQL SELECT query using ONLY these column names.\n"
        "DO NOT explain your reasoning, and DO NOT return anything other than the SQL query itself."
    )

    generated_sql = agent.run(f"{schema_info} Convert this request into SQL: {user_query}")

    if not isinstance(generated_sql, str):
        return f"{generated_sql}"  # Handle unexpected numerical result

    result = sql_engine(generated_sql)

    try:
        float_result = float(result)
        return f"{float_result:.2f}"
    except ValueError:
        return result

# Function to call query_sql and display the results in the UI
def handle_query(user_input: str) -> str:
    return query_sql(user_input)

# Initialize the agent with the necessary tools
agent = CodeAgent(
    tools=[sql_engine],
    model=HfApiModel(model_id="Qwen/Qwen2.5-Coder-32B-Instruct", token="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"),
)

# Gradio UI layout
with gr.Blocks() as demo:
    gr.Markdown("""
    <style>
        .header { font-size: 26px; font-weight: bold; color: #4C4C4C; }
        .description { color: #333333; font-size: 18px; margin-bottom: 20px; }
        .box { border: 1px solid #ccc; padding: 15px; border-radius: 12px; background-color: #f7f7f7; }
        .footer { text-align: center; font-size: 14px; color: #999999; margin-top: 20px; }
        .gradio-container { background-color: #ffffff; padding: 30px; border-radius: 12px; }
    </style>
    <div class="header">
        <img src="path_to_logo.png" style="height: 50px; vertical-align: middle; margin-right: 10px;">
        Receipts Database Query Interface
    </div>
    <div class="description">
        This tool allows you to query the receipts database using natural language. Enter your question, and the system will generate and execute an SQL query to retrieve the data.
    </div>
    """)

    with gr.Row():
        with gr.Column(scale=1):
            user_input = gr.Textbox(label="Ask a question about the data", placeholder="E.g., 'What is the total price of all receipts?'")
            query_output = gr.Textbox(label="Result", interactive=False, lines=5)

        with gr.Column(scale=2):
            gr.Markdown("### Receipts Table")
            receipts_table = gr.Dataframe(value=get_receipts_table(), label="Receipts Table", wrap=True)

    user_input.change(fn=handle_query, inputs=user_input, outputs=query_output)
    demo.load(fn=get_receipts_table, outputs=receipts_table)

    gr.Markdown("""
    <div class="footer">
        Developed by Ashish Patel. All rights reserved.
    </div>
    """)

if __name__ == "__main__":
    demo.launch(server_name="0.0.0.0", server_port=7861, share=True)

Overwriting new_sqlagent.py

In [ ]:
!python3 new_sqlagent.py

* Running on local URL:  http://0.0.0.0:7861
* Running on public URL: https://29f6558492b462c09c.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
╭──────────────────────────────────────────── New run ─────────────────────────────────────────────╮
│                                                                                                  │
│ The database has a table named 'receipts' with the following schema:                             │
│ - receipt_id (INTEGER, primary key)                                                              │
│ - customer_name (VARCHAR(16))                                                                    │
│ - price (FLOAT)                                                                                  │
│ - tip (FLOAT)                                                                                    │
│ Generate a valid SQL SELECT query using ONLY these column names.                                 │
│ DO NOT explain your reasoning, and DO NOT return anything other than the SQL query itself.       │
│ Convert this request into SQL: W                                                                 │
│                                                                                                  │
╰─ HfApiModel - Qwen/Qwen2.5-Coder-32B-Instruct ───────────────────────────────────────────────────╯
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ─ Executing parsed code: ─────────────────────────────────────────────────────────────────────────
  query = "SELECT receipt_id, customer_name, price, tip FROM receipts;"
  print(query)
 ──────────────────────────────────────────────────────────────────────────────────────────────────
Execution logs:
SELECT receipt_id, customer_name, price, tip FROM receipts;

Out: None
[Step 1: Duration 2.39 seconds| Input tokens: 2,142 | Output tokens: 50]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ─ Executing parsed code: ─────────────────────────────────────────────────────────────────────────
  final_answer("SELECT receipt_id, customer_name, price, tip FROM receipts;")
 ──────────────────────────────────────────────────────────────────────────────────────────────────
Out - Final answer: SELECT receipt_id, customer_name, price, tip FROM receipts;
[Step 2: Duration 1.35 seconds| Input tokens: 4,433 | Output tokens: 76]
╭──────────────────────────────────────────── New run ─────────────────────────────────────────────╮
│                                                                                                  │
│ The database has a table named 'receipts' with the following schema:                             │
│ - receipt_id (INTEGER, primary key)                                                              │
│ - customer_name (VARCHAR(16))                                                                    │
│ - price (FLOAT)                                                                                  │
│ - tip (FLOAT)                                                                                    │
│ Generate a valid SQL SELECT query using ONLY these column names.                                 │
│ DO NOT explain your reasoning, and DO NOT return anything other than the SQL query itself.       │
│ Convert this request into SQL: What is the total of pr                                           │
│                                                                                                  │
╰─ HfApiModel - Qwen/Qwen2.5-Coder-32B-Instruct ───────────────────────────────────────────────────╯
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ─ Executing parsed code: ─────────────────────────────────────────────────────────────────────────
  query = "SELECT SUM(price) FROM receipts;"
  final_answer(query)
 ──────────────────────────────────────────────────────────────────────────────────────────────────
Out - Final answer: SELECT SUM(price) FROM receipts;
[Step 1: Duration 1.92 seconds| Input tokens: 2,147 | Output tokens: 43]
╭──────────────────────────────────────────── New run ─────────────────────────────────────────────╮
│                                                                                                  │
│ The database has a table named 'receipts' with the following schema:                             │
│ - receipt_id (INTEGER, primary key)                                                              │
│ - customer_name (VARCHAR(16))                                                                    │
│ - price (FLOAT)                                                                                  │
│ - tip (FLOAT)                                                                                    │
│ Generate a valid SQL SELECT query using ONLY these column names.                                 │
│ DO NOT explain your reasoning, and DO NOT return anything other than the SQL query itself.       │
│ Convert this request into SQL: What is the total of prices by                                    │
│                                                                                                  │
╰─ HfApiModel - Qwen/Qwen2.5-Coder-32B-Instruct ───────────────────────────────────────────────────╯
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ─ Executing parsed code: ─────────────────────────────────────────────────────────────────────────
  query = "SELECT SUM(price) as total_price FROM receipts;"
  print(query)
 ──────────────────────────────────────────────────────────────────────────────────────────────────
Execution logs:
SELECT SUM(price) as total_price FROM receipts;

Out: None
[Step 1: Duration 1.84 seconds| Input tokens: 2,149 | Output tokens: 41]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ─ Executing parsed code: ─────────────────────────────────────────────────────────────────────────
  final_answer("SELECT SUM(price) as total_price FROM receipts;")
 ──────────────────────────────────────────────────────────────────────────────────────────────────
Out - Final answer: SELECT SUM(price) as total_price FROM receipts;
[Step 2: Duration 1.90 seconds| Input tokens: 4,432 | Output tokens: 81]
╭──────────────────────────────────────────── New run ─────────────────────────────────────────────╮
│                                                                                                  │
│ The database has a table named 'receipts' with the following schema:                             │
│ - receipt_id (INTEGER, primary key)                                                              │
│ - customer_name (VARCHAR(16))                                                                    │
│ - price (FLOAT)                                                                                  │
│ - tip (FLOAT)                                                                                    │
│ Generate a valid SQL SELECT query using ONLY these column names.                                 │
│ DO NOT explain your reasoning, and DO NOT return anything other than the SQL query itself.       │
│ Convert this request into SQL: What is the total of prices by all customer?                      │
│                                                                                                  │
╰─ HfApiModel - Qwen/Qwen2.5-Coder-32B-Instruct ───────────────────────────────────────────────────╯
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ─ Executing parsed code: ─────────────────────────────────────────────────────────────────────────
  query = sql_engine(query="SELECT SUM(price) AS total_price FROM receipts")
  print(query)
 ──────────────────────────────────────────────────────────────────────────────────────────────────
Execution logs:
1489.55

Out: None
[Step 1: Duration 1.35 seconds| Input tokens: 2,151 | Output tokens: 29]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ─ Executing parsed code: ─────────────────────────────────────────────────────────────────────────
  final_answer(1489.55)
 ──────────────────────────────────────────────────────────────────────────────────────────────────
Out - Final answer: 1489.55
[Step 2: Duration 1.17 seconds| Input tokens: 4,425 | Output tokens: 50]
╭──────────────────────────────────────────── New run ─────────────────────────────────────────────╮
│                                                                                                  │
│ The database has a table named 'receipts' with the following schema:                             │
│ - receipt_id (INTEGER, primary key)                                                              │
│ - customer_name (VARCHAR(16))                                                                    │
│ - price (FLOAT)                                                                                  │
│ - tip (FLOAT)                                                                                    │
│ Generate a valid SQL SELECT query using ONLY these column names.                                 │
│ DO NOT explain your reasoning, and DO NOT return anything other than the SQL query itself.       │
│ Convert this request into SQL: What is the total of prices by all customers?                     │
│                                                                                                  │
╰─ HfApiModel - Qwen/Qwen2.5-Coder-32B-Instruct ───────────────────────────────────────────────────╯
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ─ Executing parsed code: ─────────────────────────────────────────────────────────────────────────
  query = "SELECT SUM(price) FROM receipts;"
  final_answer(query)
 ──────────────────────────────────────────────────────────────────────────────────────────────────
Out - Final answer: SELECT SUM(price) FROM receipts;
[Step 1: Duration 1.12 seconds| Input tokens: 2,151 | Output tokens: 24]
╭──────────────────────────────────────────── New run ─────────────────────────────────────────────╮
│                                                                                                  │
│ The database has a table named 'receipts' with the following schema:                             │
│ - receipt_id (INTEGER, primary key)                                                              │
│ - customer_name (VARCHAR(16))                                                                    │
│ - price (FLOAT)                                                                                  │
│ - tip (FLOAT)                                                                                    │
│ Generate a valid SQL SELECT query using ONLY these column names.                                 │
│ DO NOT explain your reasoning, and DO NOT return anything other than the SQL query itself.       │
│ Convert this request into SQL:                                                                   │
│                                                                                                  │
╰─ HfApiModel - Qwen/Qwen2.5-Coder-32B-Instruct ───────────────────────────────────────────────────╯
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ─ Executing parsed code: ─────────────────────────────────────────────────────────────────────────
  query = "SELECT receipt_id, customer_name, price, tip FROM receipts;"
  print(query)
 ──────────────────────────────────────────────────────────────────────────────────────────────────
Execution logs:
SELECT receipt_id, customer_name, price, tip FROM receipts;

Out: None
[Step 1: Duration 2.04 seconds| Input tokens: 2,142 | Output tokens: 46]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ─ Executing parsed code: ─────────────────────────────────────────────────────────────────────────
  query = "SELECT receipt_id, customer_name, price, tip FROM receipts;"
  final_answer(query)
 ──────────────────────────────────────────────────────────────────────────────────────────────────
Out - Final answer: SELECT receipt_id, customer_name, price, tip FROM receipts;
[Step 2: Duration 2.23 seconds| Input tokens: 4,429 | Output tokens: 93]
╭──────────────────────────────────────────── New run ─────────────────────────────────────────────╮
│                                                                                                  │
│ The database has a table named 'receipts' with the following schema:                             │
│ - receipt_id (INTEGER, primary key)                                                              │
│ - customer_name (VARCHAR(16))                                                                    │
│ - price (FLOAT)                                                                                  │
│ - tip (FLOAT)                                                                                    │
│ Generate a valid SQL SELECT query using ONLY these column names.                                 │
│ DO NOT explain your reasoning, and DO NOT return anything other than the SQL query itself.       │
│ Convert this request into SQL: W                                                                 │
│                                                                                                  │
╰─ HfApiModel - Qwen/Qwen2.5-Coder-32B-Instruct ───────────────────────────────────────────────────╯
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ─ Executing parsed code: ─────────────────────────────────────────────────────────────────────────
  query = "SELECT receipt_id, customer_name, price, tip FROM receipts;"
  print(query)
 ──────────────────────────────────────────────────────────────────────────────────────────────────
Execution logs:
SELECT receipt_id, customer_name, price, tip FROM receipts;

Out: None
[Step 1: Duration 0.92 seconds| Input tokens: 2,142 | Output tokens: 50]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ─ Executing parsed code: ─────────────────────────────────────────────────────────────────────────
  final_answer("SELECT receipt_id, customer_name, price, tip FROM receipts;")
 ──────────────────────────────────────────────────────────────────────────────────────────────────
Out - Final answer: SELECT receipt_id, customer_name, price, tip FROM receipts;
[Step 2: Duration 0.08 seconds| Input tokens: 4,433 | Output tokens: 76]
╭──────────────────────────────────────────── New run ─────────────────────────────────────────────╮
│                                                                                                  │
│ The database has a table named 'receipts' with the following schema:                             │
│ - receipt_id (INTEGER, primary key)                                                              │
│ - customer_name (VARCHAR(16))                                                                    │
│ - price (FLOAT)                                                                                  │
│ - tip (FLOAT)                                                                                    │
│ Generate a valid SQL SELECT query using ONLY these column names.                                 │
│ DO NOT explain your reasoning, and DO NOT return anything other than the SQL query itself.       │
│ Convert this request into SQL: What is th                                                        │
│                                                                                                  │
╰─ HfApiModel - Qwen/Qwen2.5-Coder-32B-Instruct ───────────────────────────────────────────────────╯
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ─ Executing parsed code: ─────────────────────────────────────────────────────────────────────────
  query = "SELECT receipt_id, customer_name, price, tip FROM receipts"
  print(query)
 ──────────────────────────────────────────────────────────────────────────────────────────────────
Execution logs:
SELECT receipt_id, customer_name, price, tip FROM receipts

Out: None
[Step 1: Duration 2.22 seconds| Input tokens: 2,144 | Output tokens: 47]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ─ Executing parsed code: ─────────────────────────────────────────────────────────────────────────
  final_answer("SELECT receipt_id, customer_name, price, tip FROM receipts")
 ──────────────────────────────────────────────────────────────────────────────────────────────────
Out - Final answer: SELECT receipt_id, customer_name, price, tip FROM receipts
[Step 2: Duration 1.33 seconds| Input tokens: 4,433 | Output tokens: 71]
╭──────────────────────────────────────────── New run ─────────────────────────────────────────────╮
│                                                                                                  │
│ The database has a table named 'receipts' with the following schema:                             │
│ - receipt_id (INTEGER, primary key)                                                              │
│ - customer_name (VARCHAR(16))                                                                    │
│ - price (FLOAT)                                                                                  │
│ - tip (FLOAT)                                                                                    │
│ Generate a valid SQL SELECT query using ONLY these column names.                                 │
│ DO NOT explain your reasoning, and DO NOT return anything other than the SQL query itself.       │
│ Convert this request into SQL: What is the total prices by all                                   │
│                                                                                                  │
╰─ HfApiModel - Qwen/Qwen2.5-Coder-32B-Instruct ───────────────────────────────────────────────────╯
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ─ Executing parsed code: ─────────────────────────────────────────────────────────────────────────
  query = "SELECT SUM(price) FROM receipts"
  print(query)
 ──────────────────────────────────────────────────────────────────────────────────────────────────
Execution logs:
SELECT SUM(price) FROM receipts

Out: None
[Step 1: Duration 1.97 seconds| Input tokens: 2,148 | Output tokens: 41]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ─ Executing parsed code: ─────────────────────────────────────────────────────────────────────────
  query = "SELECT SUM(price) FROM receipts"
  final_answer(query)
 ──────────────────────────────────────────────────────────────────────────────────────────────────
Out - Final answer: SELECT SUM(price) FROM receipts
[Step 2: Duration 2.10 seconds| Input tokens: 4,423 | Output tokens: 85]
╭──────────────────────────────────────────── New run ─────────────────────────────────────────────╮
│                                                                                                  │
│ The database has a table named 'receipts' with the following schema:                             │
│ - receipt_id (INTEGER, primary key)                                                              │
│ - customer_name (VARCHAR(16))                                                                    │